START TRANSACTION;

DROP TABLE GameRoundResult;
DROP TABLE GameRound;
DROP TABLE RoshamboSelection;
DROP TABLE GamePlayer;
DROP TABLE Player;
DROP TABLE RoshamboGame;
DROP TABLE GameRuleSet;
DROP TABLE GameStatus;
COMMIT;